import React from 'react'

export const ADD_BURGER_INGREDIENTS = 'ADD_BURGER_INGREDIENTS';

export const GET_BURGER_INGREDIENTS_SUCCESS = 'GET_BURGER_INGREDIENTS_SUCCESS';

export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';

export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'

export const MOVE_INGREDIENT = 'MOVE_INGREDIENT'

